#!/usr/bin/env python3

import errno
import os
import pathlib

import requests

import api_client
import channel_log
import config
import log
import metadata

def main():
	client = api_client.APIClient()
	guilds = {}
	users = {}
	channels = {}
	try:
		for channel in client.iter_channels():
			guilds[channel.guild_id] = channel.guild_name
			channels[channel.id] = (channel.guild_id, channel.name)
			try:
				get_history(channel, users)
			except requests.exceptions.HTTPError as e:
				if e.response.status_code != 403:
					raise
	except KeyboardInterrupt:
		log.write('caught SIGINT; flushing...')
	channel_log.flush()
	metadata.write(guilds, channels, users)

def get_history(channel: api_client.Channel, users: dict):
	channel_path = pathlib.Path(channel.guild_id, channel.id)
	abspath = pathlib.Path(config.log_dir, channel_path)
	log.write('getting history for', channel_path)
	last_message_id = 0
	try:
		abspath.mkdir(parents=True)
	except FileExistsError:
		if log_files := list(abspath.iterdir()):
			last_message_id = channel_log.last_message_id(abspath / max(log_files))
			log.write('continuing from', last_message_id)

	client = api_client.APIClient()
	for message in client.iter_messages(channel.id, after_id=last_message_id):
		channel_log.log_message(channel_path, message)
		user = message['author']
		users[user['id']] = user['username']
	log.write('reached end of chat history for', channel_path)

if __name__ == '__main__':
	main()
